# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-12-25 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181221_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='html',
            field=models.TextField(default='', help_text='仅支持markdown格式后的数据', verbose_name='渲染后的内容'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_markdown',
            field=models.BooleanField(default=True, verbose_name='是否为markdown'),
        ),
    ]
